#--------------业务数据处理----------------------------
business:
  tcpServer: 
    allKeys: test1,test2,test3
    usedKey: test1
  udp: 
    allKeys: udpTest1,udpTest2,udpTest3
    usedKey: udpTest3
  http:
    allKeys: http1,http2,http3
    usedKey: http3
#--------------线程池-----------------------------
data: 
  threadPool: 
    corePoolSize: 50
    maximumPoolSize: 250
    keepAliveTim: 10000